#!/bin/sh
# $Id: use-usual,v 1.4 2024/07/15 23:55:59 tom Exp $
# Install a wrapper script for "sudo" instead of the given setuid/setgid
# program.

INSTALL="$1"; shift 1
PROGRAM="$1"; shift 1
DestDir="$1"; shift 1

if [ "$#" != 0 ]
then
	for user in "$@"
	do
		echo "** installing sudo wrapper for $user"
		cat >"$user" <<\EOF
#!/bin/sh
sudo "$@"
EOF
		chmod +x "$user"
		$INSTALL "$user" "$DestDir/$user"
		rm -f "$user"
		ls -l "$DestDir/$user"
	done
fi
