#!/bin/sh
# $Id: use-hacks,v 1.4 2012/03/14 00:53:19 tom Exp $
# install the given program as setuid/setgid for the listed users

DOIT=eval

INSTALL="$1"; shift 1
PROGRAM="$1"; shift 1
DESTDIR="$1"; shift 1

if test "$#" != 0
then
	echo "** installing setuid for $*"
	for user in $*
	do
		$DOIT $INSTALL $PROGRAM $DESTDIR/$user
		if id $user >/dev/null 2>/dev/null
		then
			echo "...$user"
			U=`id $user | sed -e 's/^uid=//' -e 's/(.*//'`
			G=`id $user | sed -e 's/^.*gid=//' -e 's/(.*//'`
			$DOIT chown $U $DESTDIR/$user
			$DOIT chgrp $G $DESTDIR/$user
			$DOIT chmod ug+s $DESTDIR/$user
		else
			echo "?? $user"
		fi
		ls -l $DESTDIR/$user
	done
fi
