.\" $Id: acmerge.1,v 1.3 2024/07/12 22:56:16 tom Exp $
.TH ACMERGE 1 2024-07-12 "MiscTools" "User commands"
.ie \n(.g \{\
.ds `` \(lq
.ds '' \(rq
.\}
.el \{\
.ie t .ds `` ``
.el   .ds `` ""
.ie t .ds '' ''
.el   .ds '' ""
.\}
.hy 0
.SH NAME
acmerge \-
merge a split aclocal.m4
.SH SYNOPSIS
.B acmerge
[
.I filename
]
.
.SH DESCRIPTION
Merge parts for a split-up autoconf source file (usually
aclocal.m4) from a parent file which was processed by
\fBacsplit\fP.
.PP
The command parameter tells \fBacmerge\fP where to write merged autoconf
source (default: \*(``aclocal.m4\*('').
.
.SH OPTIONS
.TP 5
.B \-n
do not create a comment-line with dashes between macros in the resulting file.
.TP 5
.B \-v
verbose
.
.
.SH BUGS
.
Probably.
.
.SH EXAMPLES
.
\fBAcmerge\fR is used to construct aclocal.m4 from the macros which are
stored in a repository.
.
.SH SEE ALSO
acsplit(1)
