.\" $Id: acsplit.1,v 1.3 2024/07/12 22:56:16 tom Exp $
.TH ACSPLIT 1 2024-07-12 "MiscTools" "User commands"
.ie \n(.g \{\
.ds `` \(lq
.ds '' \(rq
.\}
.el \{\
.ie t .ds `` ``
.el   .ds `` ""
.ie t .ds '' ''
.el   .ds '' ""
.\}
.hy 0
.SH NAME
acsplit \-
split a terminfo source-file
.SH SYNOPSIS
.B acsplit
[
.I options
] [
.I filename
[
.I ...
]
]
.
.SH DESCRIPTION
Splits an autoconf macro file file (usually aclocal.m4) into
a parent file which can be reprocessed by acmerge, and
the entries in a \*(``AcSplit\*('' subdirectory.
.PP
If no filename is given, this splits \*(``aclocal.m4\*(''
.PP
While splitting, \fBacsplit\fP creates a map of the input file,
named for the input with \*(``.in\*('' appended,
e.g., \*(``aclocal.m4.in\*(''
(used by \fBacmerge\fP when reconstructing the original file).
.
.SH OPTIONS
.
.TP 5
.B \-v
verbose, printing the filenames which are split.
.
.
.SH BUGS
.
Probably.
.
.SH EXAMPLES
.
\fBAcsplit\fR is used to maintain the aclocal.m4 files whose macros
are stored in a repository.
.
.SH SEE ALSO
acmerge(1)
