.\" $Id: isatty.1,v 1.3 2024/07/12 22:56:16 tom Exp $
.TH ISATTY 1 2024-07-12 "MiscTools" "User commands"
.ie n .ds CW R
.el   \{
.ie \n(.g .ds CW CR
.el       .ds CW CW
.\}
.de NE
.fi
.ft R
.ie n  .in -4
.el    .in -2
..
.de NS
.ie n  .sp
.el    .sp .5
.ie n  .in +4
.el    .in +2
.nf
.ft \*(CW
..
.
.hy 0
.SH NAME
isatty \-
check if standard I/O is a tty
.SH SYNOPSIS
.B isatty
.
.SH DESCRIPTION
Use \fBisatty\fR to check if the standard input and output are a terminal.
.
.SH OPTIONS
None
.
.
.SH BUGS
.
Probably.
.
.SH EXAMPLES
.
\fBIsatty\fR is equivalent to
.
.NS 4
[ \-t 0 ] && [ \-t 1 ]
.NE
.
.SH SEE ALSO
test
