.\" $Id: map.1,v 1.3 2024/07/12 22:56:16 tom Exp $
.TH MAP 1 2024-07-12 "MiscTools" "User commands"
.hy 0
.SH NAME
map \-
encode typescript files
.SH SYNOPSIS
.B map
[
.I options
] [
.I filename
[
.I ...
]
]
.
.SH DESCRIPTION
Translate one or more files produced by unmap
back into a mixture of control characters and text.
If no filename is given, read from the standard input.
.
.SH OPTIONS
.TP 5
.B \-u
encode bytes into UTF-8 Unicode, where appropriate.
.
.
.SH BUGS
.
Probably.
.
.
.SH EXAMPLES
.
\fBMap\fR is used to convert readable-format files
back into controls, which can be replayed on the terminal.
.
.SH SEE ALSO
unmap(1)
