.\" $Id: map.1,v 1.1 2020/10/26 00:04:35 tom Exp $
.TH MAP "1" "October 2020"
.hy 0
.SH NAME
map \- encode typescript files
.
.SH SYNOPSIS
.B map
[
.I options
] [
.I filename
[
.I ...
]
]
.
.SH DESCRIPTION
Translate one or more files produced by unmap
back into a mixture of control characters and text.
If no filename is given, read from the standard input.
.
.SH OPTIONS
.TP 5
.B \-u
encode bytes into UTF-8 Unicode, where appropriate.
.
.
.SH USAGE
.
\fBMap\fR is used to convert readable-format files
back into controls, which can be replayed on the terminal.
.
.SH SEE ALSO
unmap(1)
.
.
.SH BUGS
.
Probably.
