.\" $Id: newest.1,v 1.3 2024/07/12 22:56:16 tom Exp $
.TH NEWEST 1 2024-07-12 "MiscTools" "User commands"
.hy 0
.SH NAME
newest \-
display name or timestamp of newest file
.SH SYNOPSIS
.B newest
[
.I options
] [
.I filename
[
.I ...
]
]
.
.SH DESCRIPTION
Given one or more files specified either on the command line, or via a pipe,
compute the date and/or name of the newest one, printing to stdout.
.PP
If filenames are given as parameters,
display those names/timestamps.
Otherwise, read the list of filenames from a pipe.
.
.SH OPTIONS
.TP 5
.B \-d
print the date/timestamp
.
.TP 5
.B \-n
print the filename
.
.PP
If both options are given, print both, separated by a tab.
The filename comes first, in that case.
.
.
.SH BUGS
.
Probably.
.
.
.SH EXAMPLES
.
\fBNewest\fR is used in shell scripts
to find the newest file's timestamp in a collection.
.
.SH SEE ALSO
cpd(1).
