.\" $Id: perror.1,v 1.4 2024/07/12 22:56:16 tom Exp $
.TH PERROR 1 2024-07-12 "MiscTools" "User commands"
.hy 0
.SH NAME
perror \-
print messages for errno values
.SH SYNOPSIS
.B perror
[
.I errno1
[
.I ...
]
]
.
.SH DESCRIPTION
Use \fBperror\fR to print the messages corresponding to \fBerrno\fP value.
This accepts one or more parameters, which must be integers.
.
.SH OPTIONS
None.
.
.
.SH BUGS
.
Probably.
.
.SH EXAMPLES
.
\fBPerror\fR is used to lookup the message for a given \fBerrno\fP value.
.
.SH SEE ALSO
errno(3)
