.\" $Id: sue.1,v 1.5 2024/07/12 22:56:16 tom Exp $
.TH SUE 1 2024-07-12 "MiscTools" "User commands"
.ie \n(.g \{\
.ds `` \(lq
.ds '' \(rq
.\}
.el \{\
.ie t .ds `` ``
.el   .ds `` ""
.ie t .ds '' ''
.el   .ds '' ""
.\}
.hy 0
.SH NAME
sue \-
su with environment
.SH SYNOPSIS
.B sue
.I command
.
.SH DESCRIPTION
Provides a \*(``su\*('' command which preserves caller's environment.
.PP
\fBSue\fR may be a wrapper for \fBsudo\fP (e.g., to the \fIroot\fP user).
For non-root use, the setuid configuration is preferred,
because \fBsudo\fP makes it cumbersome to reuse the current \fBPATH\fP.
.
.SH OPTIONS
None.
.
.
.SH BUGS
.
Probably.
.
.SH EXAMPLES
.
\fBSue\fR is installed by convention as the user to which it should \*(``su\*(''
.
.SH SEE ALSO
sudo, su
