.\" $Id: timerge.1,v 1.4 2024/07/12 22:56:16 tom Exp $
.TH TIMERGE 1 2024-07-12 "MiscTools" "User commands"
.ie \n(.g \{\
.ds `` \(lq
.ds '' \(rq
.\}
.el \{\
.ie t .ds `` ``
.el   .ds `` ""
.ie t .ds '' ''
.el   .ds '' ""
.\}
.hy 0
.SH NAME
timerge \-
merge a split terminfo.src
.SH SYNOPSIS
.B timerge
[
.I filename
]
.
.SH DESCRIPTION
Merge parts for a split-up terminfo source file (usually
terminfo.src) from a parent file which was processed by
\fBtisplit\fP.
.PP
The command parameter tells \fBtimerge\fP where to write merged terminfo
source (default: \*(``terminfo.src\*('').
.
.SH OPTIONS
None.
.
.
.SH BUGS
.
Probably.
.
.SH EXAMPLES
.
\fBTimerge\fR is used to compare sources for large terminfo databases.
.
.SH SEE ALSO
tisplit
