.\" $Id: tisplit.1,v 1.5 2024/07/12 22:56:16 tom Exp $
.TH TISPLIT 1 2024-07-12 "MiscTools" "User commands"
.ie \n(.g \{\
.ds `` \(lq
.ds '' \(rq
.\}
.el \{\
.ie t .ds `` ``
.el   .ds `` ""
.ie t .ds '' ''
.el   .ds '' ""
.\}
.hy 0
.SH NAME
tisplit \-
split a terminfo source-file
.SH SYNOPSIS
.B tisplit
[
.I options
] [
.I filename
[
.I ...
]
]
.
.SH DESCRIPTION
Splits a terminfo file (usually terminfo.src) into
a parent file which can be reprocessed by timerge, and
the entries in a \*(``TiSplit\*('' subdirectory.
.PP
If no filename is given, this splits \*(``terminfo.src\*(''
.PP
While splitting, \fBtisplit\fP creates a map of the input file,
named for the input with \*(``.in\*('' appended,
e.g., \*(``terminfo.src.in\*(''
(used by \fBtimerge\fP when reconstructing the original file).
.
.SH OPTIONS
.
.TP 5
.B \-v
verbose, printing the filenames which are split.
.
.
.SH BUGS
.
Probably.
.
.SH EXAMPLES
.
\fBTisplit\fR is used to compare sources for large terminfo databases.
.
.SH SEE ALSO
timerge
