.\" $Id: width.1,v 1.4 2020/10/25 23:50:40 tom Exp $
.de bP
.ie n  .IP \(bu 4
.el    .IP \(bu 2
..
.de NE
.fi
.ft R
.ie n  .in -4
.el    .in -2
..
.de NS
.ie n  .sp
.el    .sp .5
.ie n  .in +4
.el    .in +2
.nf
.ft C			\" Courier
..
.
.TH WIDTH "1" "October 2020"
.hy 0
.SH NAME
width \- display width of lines in a text file
.
.SH SYNOPSIS
.B width
[
.I options
] [
.I filename
[
.I ...
]
]
.
.SH DESCRIPTION
Use \fBwidth\fR to
.bP
find the length of the longest line in one or more files, or
.bP
show lines that are longer than a given threshold
.
.SH OPTIONS
.TP 5
.B \-4
set tab stops to multiples of 4 (e.g., 1, 5, 9, ...)
.
.TP 5
.B \-8
set tab stops to multiples of 4 (e.g., 1, 9, 17, ...)
.
.TP 5
.B \-n
show line-numbers of wide lines, prefixed by the corresponding filename.
Several text editors (e.g., vile, emacs) treat this style of output as
an error listing, and can step through the reported instances.
.
.TP 5
.B \-p
report maximum width per-file (otherwise the maximum across all files
is reported).
.
.TP 5
.BI \-t NUM
set tab stops to multiples of \fINUM\fP.
The default tab-stop interval is 8.
.
.TP 5
.BI \-w NUM
report lines longer than \fINUM\fP.
.
.
.SH USAGE
.
\fBWidth\fR is normally used to check the width of production-quality
C/C++ code, e.g.,
.
.NS 4
width -w79 -4 -n $*
.NE
.
.PP
Use a "-" in place of the \fI[filename]\fR to read a list of filenames
from the standard input.
.
.SH SEE ALSO
indent
.
.
.SH BUGS
.
Probably.
